use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(UserStatistics::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(UserStatistics::UserId)
                            .text()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::HandsPlayed)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::HandsWon)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::VpipHands)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::PfrHands)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::PreflopFoldCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::Showdowns)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::ShowdownWins)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::HandsWithoutShowdown)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::TotalWagered)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::TotalWon)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::NetProfit)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::BiggestPotWon)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::AllInCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::Bets)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::Raises)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::Calls)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(UserStatistics::LastHandPlayedAt).text())
                    .col(ColumnDef::new(UserStatistics::LastHandId).text())
                    .col(
                        ColumnDef::new(UserStatistics::LastUpdatedAt)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserStatistics::Version)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(UserStatistics::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum UserStatistics {
    Table,
    UserId,
    HandsPlayed,
    HandsWon,
    VpipHands,
    PfrHands,
    PreflopFoldCount,
    Showdowns,
    ShowdownWins,
    HandsWithoutShowdown,
    TotalWagered,
    TotalWon,
    NetProfit,
    BiggestPotWon,
    AllInCount,
    Bets,
    Raises,
    Calls,
    LastHandPlayedAt,
    LastHandId,
    LastUpdatedAt,
    Version,
}
