[package]
name = "sb-bot-handler"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["time"] }
parking_lot = { workspace = true }
sb-contracts = { workspace = true }
sb-shared-types = { workspace = true }

axum = { workspace = true }
teloxide = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
