#!/usr/bin/env bash
set -uo pipefail

cd tools/sb-cards/card-compositor-renderer || exit 1

# ----------------------------------------------------------------------
# 1. Create symlinks for assets so they are served from /public
# ----------------------------------------------------------------------
echo "Creating symlinks for asset folders"

# Remove existing links/directories if they exist
rm -rf public/2-pips public/fonts public/corner-light.png

# Link to the actual 2-pips folder (generated by Python script)
# The deck base directory is ../2026-Q1/01-poison-gardenia relative to project root.
# From project root (tools/sb-cards/card-compositor-renderer), the target is ../../../2026-Q1/01-poison-gardenia/2-pips
# But the config uses "../2026-Q1/01-poison-gardenia" which is one level up from project root.
# The actual absolute path is ../../..? Let's compute:
# Project root: /Users/adm/Documents/Repos/stackbluff/tools/sb-cards/card-compositor-renderer
# Deck folder: /Users/adm/Documents/Repos/stackbluff/2026-Q1/01-poison-gardenia
# So relative link: ../../../2026-Q1/01-poison-gardenia/2-pips

if [ -d "../../../2026-Q1/01-poison-gardenia/2-pips" ]; then
    ln -sf "../../../2026-Q1/01-poison-gardenia/2-pips" public/2-pips
    echo "Linked public/2-pips -> ../../../2026-Q1/01-poison-gardenia/2-pips"
else
    echo "WARNING: 2-pips folder not found. Run the Python script first to generate pips."
    mkdir -p public/2-pips
fi

# Link fonts if available
if [ -d "../../../engine/fonts" ]; then
    ln -sf "../../../engine/fonts" public/fonts
    echo "Linked public/fonts -> ../../../engine/fonts"
else
    mkdir -p public/fonts
    echo "Created empty fonts directory"
fi

# Ensure corner-light.png exists (generate if missing)
if [ ! -f public/corner-light.png ]; then
    echo "Generating corner-light.png using ImageMagick or fallback"
    if command -v convert &>/dev/null; then
        convert -size 1000x1400 radial-gradient:white-transparent public/corner-light.png
    else
        # Create a blank transparent PNG using Node.js (if available)
        if command -v node &>/dev/null; then
            node -e "const fs=require('fs'); const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAA+gAAAPoAQMAAAB2J9EhAAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAAlwSFlzAAAOxAAADsQBlSsOGwAAADFJREFUeJztwTEBAAAAwqD1T20KP6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4G8AB4cAARjNuZUAAAAASUVORK5CYII=', 'base64'); fs.writeFileSync('public/corner-light.png', png);" || echo "Could not create corner-light.png"
        fi
    fi
fi

# ----------------------------------------------------------------------
# 2. Patch DeckViewer to make cards responsive (scale 1000x1400 down)
# ----------------------------------------------------------------------
echo "Updating DeckViewer with responsive scaling"
cat > src/components/DeckViewer.tsx << 'DECK_VIEWER_RESP'
import React from 'react';
import { Card } from './Card';
import { CardData } from '../types';

interface Props {
  cards: CardData[];
  deckName: string;
}

export const DeckViewer: React.FC<Props> = ({ cards, deckName }) => {
  const cardWidth = 260; // pixels for preview
  const scale = cardWidth / 1000; // 1000 is original card width
  const scaledHeight = 1400 * scale;

  return (
    <div className="grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-8 justify-items-center p-4">
      {cards.map((card, idx) => (
        <div key={idx} className="cursor-pointer transition-transform hover:scale-105" style={{ width: cardWidth }}>
          <div
            style={{
              width: 1000,
              height: 1400,
              transform: `scale(${scale})`,
              transformOrigin: 'top left',
            }}
          >
            <Card
              rank={card.rank}
              suit={card.suit}
              artPath={card.artPath}
              isBack={card.isBack}
              layoutType={card.layoutType}
              deckName={deckName}
            />
          </div>
          <div style={{ height: scaledHeight - 1400 * scale }} /> {/* maintain spacing */}
        </div>
      ))}
    </div>
  );
};
DECK_VIEWER_RESP

# ----------------------------------------------------------------------
# 3. Fix asset paths in Card.tsx to use correct URLs with leading slash
# Already using "/corner-light.png" and "/2-pips/..." – those will now work via symlinks.
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# 4. Run TypeScript check
# ----------------------------------------------------------------------
echo "Running TypeScript check"
if npx tsc --noEmit 2>&1; then
    echo "TypeScript check passed"
    COMPILE_OK=true
else
    echo "TypeScript errors detected – will continue"
    COMPILE_OK=false
fi

# ----------------------------------------------------------------------
# 5. Commit changes
# ----------------------------------------------------------------------
if [ "$COMPILE_OK" = true ]; then
    git add -A
    git commit -m "feat: add asset symlinks and responsive scaling"
    echo "✅ Commit successful"
else
    echo "⚠️ TypeScript errors remain, commit skipped"
    exit 1
fi
