[workspace]
resolver = "2"
members = [
    "crates/sb-shared-types",
    "crates/sb-contracts",
    "migration",
]

[workspace.dependencies]
# Shared
uuid = { version = "1.23.0", features = ["v4", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
derive_more = "2.1.1"
tracing = "0.1.44"

# SeaORM for migration only (not in shared-types or contracts)
sea-orm-migration = "2.0.0-rc.38"
tokio = { version = "1.52.3", features = ["full"] }
