[workspace]
resolver = "2"
members = [
    "crates/sb-db-repos",
    "crates/sb-db-entities",
    "crates/sb-shared-types",
    "crates/sb-contracts",
    "migration",
]

[workspace.dependencies]
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "tls-rustls"] }
moka = { version = "0.12", features = ["sync"] }
async-trait = "0.1.89"
anyhow = "1.0.102"
sea-orm = { version = "2.0.0-rc.38", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = { version = "2.0.0-rc.38" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
uuid = { version = "1.23.0", features = ["v7", "serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
derive_more = "2.1.1"
tokio = { version = "1.52.3", features = ["rt", "macros"] }
thiserror = "2.0.18"
tracing = "0.1.44"

[workspace.package]
edition = "2024"
rust-version = "1.94"
