[package]
name = "sbdc-service"
version = "0.1.0"
edition = "2021"

[dependencies]
sbdc-entity = { path = "../sbdc-entity" }
sbdc-dto = { path = "../sbdc-dto" }
sea-orm = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
