[package]
name = "sb-server"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[features]
default = ["test-stubs"]
test-stubs = []

[dependencies]
sb-ws-handler = { path = "../sb-ws-handler" }
sb-table-registry = { path = "../sb-table-registry" }
tower-cookies = "0.11"
sb-anti-cheat = { path = "../sb-anti-cheat" }
sb-bot-handler = { workspace = true }
sb-rest-router = { workspace = true }
sb-oracle = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sb-club = { path = "../sb-club" }
sb-db-repos = { path = "../sb-db-repos" }
sb-auth = { path = "../sb-auth" }
sb-contracts = { path = "../sb-contracts" }
sb-shared-types = { path = "../sb-shared-types" }
sea-orm = { workspace = true }
migration = { path = "../../migration" }
serde_json = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
uuid = { workspace = true }
moka = { workspace = true }
sea-orm-migration = { workspace = true }
