[package]
name = "sb-server"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[features]
default = []
test-stubs = []

[dependencies]
sentry = { version = "0.48.4", features = ["tower-axum-matched-path", "tracing", "anyhow"] }
prometheus = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
sb-ws-handler = { path = "../sb-ws-handler" }
sb-table-registry = { path = "../sb-table-registry" }
tower-cookies = "0.11"
sb-anti-cheat = { path = "../sb-anti-cheat" }
sb-poker-bots = { path = "../sb-poker-bots" }
sb-bot-handler = { workspace = true }
dotenvy = "0.15"
tower = "0.5.3"
sb-rest-router = { workspace = true }
sb-mission = { workspace = true }
sb-oracle = { workspace = true }
axum.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
tower-http = { version = "0.6", features = ["cors", "compression-gzip"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sb-club = { path = "../sb-club" }
sb-db-repos = { path = "../sb-db-repos" }
sb-auth = { path = "../sb-auth" }
sb-contracts = { path = "../sb-contracts" }
sb-shared-types = { path = "../sb-shared-types" }
sea-orm.workspace = true
migration = { path = "../../migration" }
async-trait.workspace = true
parking_lot = { workspace = true }
uuid = { workspace = true }
moka = { workspace = true }
sea-orm-migration = { workspace = true }
aws-sdk-s3 = "1.137.0"
aws-config = "1.8.18"
tokio-cron-scheduler = { workspace = true }
chrono.workspace = true
sb-db-entities.workspace = true
sb-tournament = { path = "../sb-tournament" }
serde.workspace = true
bytes = { workspace = true }
sb-viral = { path = "../sb-viral" }
sb-notification = { path = "../sb-notification" }   # <-- ADD
sb-payment = { path = "../sb-payment" }

[dev-dependencies]
mockall.workspace = true
sea-orm = { workspace = true, features = ["sqlx-sqlite"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
