[package]
name = "migration"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[dependencies]

sb-db-entities = { path = "../crates/sb-db-entities" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

uuid = { workspace = true, features = ["v4"] }
serde_json = { workspace = true }
chrono = { workspace = true }

sea-orm-migration = { workspace = true }
async-trait = { workspace = true }