[package]
name = "sb-club"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[dependencies]
moka = { workspace = true }
prometheus = { workspace = true }
sb-contracts = { path = "../sb-contracts" }
sb-shared-types = { path = "../sb-shared-types" }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
sb-db-repos = { path = "../sb-db-repos" }
sb-db-entities = { path = "../sb-db-entities" }
sea-orm = { workspace = true }
migration = { path = "../../migration" }
chrono = { workspace = true }
sea-orm-migration = { workspace = true }
