[package]
name = "sb-game-engine"
version = "0.1.0"
edition.workspace = true

[dependencies]
uuid = { workspace = true, features = ["v4"] }
sb-ws-messages = { path = "../sb-ws-messages" }
sb-shared-types = { workspace = true }
sb-contracts = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
strum = { workspace = true, features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "hand_eval"
harness = false

