[package]
name = "sb-game-engine"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[dependencies]
sb-shared-types = { path = "../sb-shared-types" }
rand = { workspace = true, features = ["std_rng", "getrandom"] }
strum = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
rand = { workspace = true, features = ["std_rng"] }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "hand_eval"
harness = false

