/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubsIndexRouteImport } from './routes/clubs/index'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments/$tournamentId'
import { Route as TableTableIdRouteImport } from './routes/table/$tableId'
import { Route as ClubsJoinRouteImport } from './routes/clubs/join'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/$tournamentId',
  path: '/$tournamentId',
  getParentRoute: () => TournamentsRoute,
} as any)
const TableTableIdRoute = TableTableIdRouteImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsJoinRoute = ClubsJoinRouteImport.update({
  id: '/clubs/join',
  path: '/clubs/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/clubs/join': typeof ClubsJoinRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/clubs/': typeof ClubsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/clubs/join': typeof ClubsJoinRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/clubs': typeof ClubsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/clubs/join': typeof ClubsJoinRoute
  '/table/$tableId': typeof TableTableIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/clubs/': typeof ClubsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/guide'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/tournaments'
    | '/verify-email'
    | '/clubs/$clubId'
    | '/clubs/join'
    | '/table/$tableId'
    | '/tournaments/$tournamentId'
    | '/clubs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/guide'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/tournaments'
    | '/verify-email'
    | '/clubs/$clubId'
    | '/clubs/join'
    | '/table/$tableId'
    | '/tournaments/$tournamentId'
    | '/clubs'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/guide'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/tournaments'
    | '/verify-email'
    | '/clubs/$clubId'
    | '/clubs/join'
    | '/table/$tableId'
    | '/tournaments/$tournamentId'
    | '/clubs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  ClubsClubIdRoute: typeof ClubsClubIdRoute
  ClubsJoinRoute: typeof ClubsJoinRoute
  TableTableIdRoute: typeof TableTableIdRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/table/$tableId': {
      id: '/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof TableTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/join': {
      id: '/clubs/join'
      path: '/clubs/join'
      fullPath: '/clubs/join'
      preLoaderRoute: typeof ClubsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TournamentsRouteChildren {
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  LeaderboardRoute: LeaderboardRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  ClubsClubIdRoute: ClubsClubIdRoute,
  ClubsJoinRoute: ClubsJoinRoute,
  TableTableIdRoute: TableTableIdRoute,
  ClubsIndexRoute: ClubsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
