[package]
name = "sb-db-repos"
version = "0.1.0"
edition.workspace = true

[dependencies]
uuid = { workspace = true }

sb-shared-types = { workspace = true }
sb-contracts = { workspace = true }
sb-db-entities = { workspace = true }
async-trait = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
tracing = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
