[package]
name = "sb-db-repos"
version = "0.1.0"
edition = "2024"

[dependencies]
sb-shared-types = { workspace = true }
sb-contracts = { workspace = true }
sb-db-entities = { workspace = true }

tokio = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
derive_more = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tempfile = "3.14"
tokio = { workspace = true, features = ["rt", "macros", "test-util"] }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"] }
