[package]
name = "sb-anti-cheat"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
metrics = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
sb-shared-types = { path = "../sb-shared-types" }
sb-contracts = { path = "../sb-contracts" }
sb-db-entities = { path = "../sb-db-entities" }
tokio = { workspace = true, features = ["rt", "time"] }
anyhow = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
moka = { workspace = true }
