[package]
name = "sb-shared-types"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"

[dependencies]

thiserror = { workspace = true }
derive_more = { workspace = true, features = ["display", "from", "into", "add"] }
tracing = { workspace = true }


chrono = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true, features = ["derive"] }