[package]
name = "sb-auth"
version = "0.1.0"
edition.workspace = true

[dependencies]
sb-shared-types = { path = "../sb-shared-types" }
async-trait = { workspace = true }
tracing.workspace = true
uuid = { workspace = true }
axum.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
tower.workspace = true

[dev-dependencies]
chrono.workspace = true
sb-contracts = { path = "../sb-contracts" }
secrecy.workspace = true
tokio.workspace = true
