import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1b1b',
        'surface-container': '#1f1f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#c7c6cb',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#303030',
        outline: '#919095',
        'outline-variant': '#46464b',
        'surface-tint': '#c6c6cf',
        primary: '#c6c6cf',
        'on-primary': '#2f3037',
        'primary-container': '#a1a1aa',
        'on-primary-container': '#37383f',
        'inverse-primary': '#5d5e66',
        secondary: '#c7c6c9',
        'on-secondary': '#303033',
        'secondary-container': '#464749',
        'on-secondary-container': '#b6b5b7',
        tertiary: '#4edea3',
        'on-tertiary': '#003824',
        'tertiary-container': '#0cb880',
        'on-tertiary-container': '#00412b',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#131313',
        'on-background': '#e2e2e2',
      },
      borderRadius: { sm: '0.25rem', DEFAULT: '0.5rem', md: '0.75rem', lg: '1rem', xl: '1.5rem', full: '9999px' },
      spacing: { unit: '4px', gutter: '24px', 'margin-mobile': '16px', 'margin-desktop': '48px', 'container-max': '1440px' },
      fontFamily: { 'display-lg': ['Playfair Display', 'serif'], 'headline-md': ['Inter', 'sans-serif'], 'body-base': ['Inter', 'sans-serif'], 'data-mono': ['JetBrains Mono', 'monospace'], 'label-caps': ['JetBrains Mono', 'monospace'] },
      fontSize: { 'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }], 'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }], 'headline-md': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }], 'body-base': ['16px', { lineHeight: '1.6', fontWeight: '400' }], 'data-mono': ['14px', { lineHeight: '1.5', letterSpacing: '0.02em', fontWeight: '500' }], 'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }] },
      keyframes: { float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-4px)' } }, sweep: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(200%)' } } },
      animation: { float: 'float 4s infinite ease-in-out', sweep: 'sweep 3s infinite linear' },
      aspectRatio: { 'table-desktop': '2.2 / 1' },
    },
  },
  plugins: [],
} as Config;
