#!/usr/bin/env bash
echo "=== SBDC Development Setup ==="
echo "1. Build the extension:"
echo "   cd tools/sbdc/sbdc-extension && ./build.sh"
echo ""
echo "2. Start the Rust server:"
echo "   cargo run --bin sbdc -- serve --deck YOUR_DECK_ID --port 8899"
echo ""
echo "3. Load extension in Chrome:"
echo "   - Open chrome://extensions/"
echo "   - Enable Developer mode"
echo "   - Click 'Load unpacked' and select tools/sbdc/sbdc-extension/dist"
echo ""
echo "4. Open https://perchance.org/fluxgen"
echo ""
echo "5. Click extension icon, set server URL (http://localhost:8899), deck ID, takes, and start generation."
