#!/usr/bin/env bash
set -euo pipefail

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           SBDC — StackBluff Deck Creator                    ║"
echo "║           Coherent Extension + Server Flow                  ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "=== PHASE 1: SETUP (CLI) ==="
echo ""
echo "1. Initialize project (seeds universe, clans, characters):"
echo "   cargo run --bin sbdc -- init"
echo ""
echo "2. Scaffold a deck (creates 52 prompt slots + narrative arcs):"
echo "   cargo run --bin sbdc -- scaffold --deck-id mydeck --season-id default_season"
echo ""
echo "3. (Optional) Ingest lore/narrative overrides:"
echo "   cargo run --bin sbdc -- ingest-json --deck-id mydeck --file lore.json"
echo ""
echo "4. Build prompts (assembles final_positive from all layers):"
echo "   cargo run --bin sbdc -- build-prompts --deck-id mydeck"
echo ""
echo "=== PHASE 2: GENERATE (Server + Extension) ==="
echo ""
echo "5. Start the server:"
echo "   cargo run --bin sbdc -- serve --port 8899"
echo ""
echo "6. Build and load the Chrome extension:"
echo "   cd tools/sbdc/sbdc-extension && ./build.sh"
echo "   → Open chrome://extensions/"
echo "   → Enable Developer mode"
echo "   → Click 'Load unpacked' and select tools/sbdc/sbdc-extension/dist"
echo ""
echo "7. Open https://perchance.org/fluxgen"
echo ""
echo "8. Click the SBDC extension icon:"
echo "   → Set Server URL: http://localhost:8899"
echo "   → Set Deck ID: mydeck"
echo "   → Set Takes per prompt: 4"
echo "   → Click 'Start' — this loads prompts into the generation queue"
echo "   → Click 'Status' to check progress"
echo ""
echo "9. The content script on perchance.org/fluxgen will:"
echo "   → Automatically fetch the next prompt from /api/decks/mydeck/prompts/next"
echo "   → Fill the positive/negative textareas"
echo "   → Click Generate"
echo "   → Wait for images to render"
echo "   → Submit takes to /api/decks/mydeck/prompts/{id}/takes"
echo "   → Repeat until all prompts are done"
echo ""
echo "=== PHASE 3: REVIEW & FINALIZE (Extension + CLI) ==="
echo ""
echo "10. Review takes (extension or API):"
echo "    GET http://localhost:8899/api/decks/mydeck/takes"
echo ""
echo "11. Select best takes (extension or API):"
echo "    POST http://localhost:8899/api/decks/mydeck/takes/{take_id}/select"
echo ""
echo "12. Finalize with clean:"
echo "    cargo run --bin sbdc -- clean --deck-id mydeck"
echo "    → Copies selected takes to 3-clean/ with final naming"
echo ""
echo "=== API REFERENCE ==="
echo ""
echo "  POST /api/decks/{deck_id}/start           — Start generation queue"
echo "  GET  /api/decks/{deck_id}/status          — Deck progress"
echo "  GET  /api/decks/{deck_id}/prompts/next    — Next prompt to generate"
echo "  POST /api/decks/{deck_id}/prompts/{id}/takes — Submit generated images"
echo "  GET  /api/decks/{deck_id}/takes           — List all takes"
echo "  POST /api/decks/{deck_id}/takes/{id}/select — Select best take"
echo ""
